### ISSUE TITLE
nick_blacklist not showing?

### ISSUE THREAD

**Issue by benoliver999** [jreese/znc-push#156]
I have a nick_blacklist that I'm loading from a config file, it looks like this:

    nick_blacklist nick1 nick2

When I type `get` in the `*push` window it only prints nick1 like so:

    +------------------------+--------------------------------+
     | Option                 | Value                         |
    +------------------------+--------------------------------+
     | nick_blacklist        | IdleBot                        |
    +------------------------+--------------------------------+

Am I missing something obvious? ~~Is the blacklist working despite this?~~ *Just got pinged*

**Comment by jreese** [comment]
Do note that if you edit the config file by hand, you'll need to either completely stop ZNC before making the changes, or manually unload znc-push, tell ZNC to rehash the config file, and then load znc-push again.  Otherwise, changes to the config file will not take effect.

You'll probably have much better luck doing something like `/msg *push set nick_blacklist nick1 nick2`, which will both update the running config and update the on-disk config file immediately.

**Comment by benoliver999** [comment]
Ah thank you, that did the trick. Funnily enough I've found I've not had to do that for some settings that were giving me problems, namely the pushover ones. I have been using the `load` command.

**Comment by benoliver999** [comment]
Of course now I think about it the reason I was using a conf file in the first place was to quickly port the settings over to each network - no longer an issue now this can be run as a user service.
