### ISSUE TITLE
Trying to send a test message without any networks crashes ZNC

### ISSUE THREAD

**Issue by johnlage** [jreese/znc-push#231]
See title. I got a blank user (no networks), then tried to set up and test *push, and doing so crashed ZNC.

**Comment by dgw** [comment]
This is almost certainly caused by https://github.com/jreese/znc-push/blob/dcb1939b8597cb19662e773ca27e2a8664e07875/push.cpp#L262 calling `GetNetwork()` when none exists.

ZNC's module header has this to say about `GetNetwork()`:

````
    /** @returns nullptr except when we are in a network-specific module hook in
     *           which case this is the network for which the hook is called.
     */
````

Obviously, `nullptr` has no `GetName()` method.

This is probably a trivial fix, if you feel like submitting a PR. Or if you don't, I will, "soon". :)
